name: Build and Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: S3

    steps:
      - uses: actions/checkout@main

      # Use Node.js for the build step
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Build the project
      - name: Build
        run: npm run build

      # Deploy to S3
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --exclude '.git/*'
        env:
          AWS_S3_BUCKET: "angular-ci-s3"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-north-1" # change this to your AWS region
          SOURCE_DIR: "dist" # change this to the directory containing your built application
